;;; -*- Mode: Lisp; Syntax: Common-Lisp; Package: org.langband.vanilla -*-

#|

DESC: variants/vanilla/config/flavours.lisp - flavours for vanilla variant
Copyright (c) 2000-2002 - Stig Erik Sandø

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

|#

(in-package :org.langband.vanilla)

(define-flavour-type '<potion> :text-sym (text-paint-value +term-white+ #\!))
(define-flavour-type '<ring> :text-sym (text-paint-value +term-white+ #\=))
(define-flavour-type '<amulet> :text-sym (text-paint-value +term-white+ #\"))
(define-flavour-type '<staff> :text-sym (text-paint-value +term-white+ #\_))
(define-flavour-type '<wand> :text-sym (text-paint-value +term-white+ #\-))
(define-flavour-type '<rod> :text-sym (text-paint-value +term-white+ #\-))
(define-flavour-type '<mushroom> :text-sym (text-paint-value +term-white+ #\,))
;; scrolls are defined at the end of this file and in various.lisp

(define-basic-flavour '<potion> "clear"               :text-sym (text-paint-value +term-white+ #\!)
                                                      :gfx-sym (tile-paint-value 11 26))
(define-basic-flavour '<potion> "light brown"         :text-sym (text-paint-value +term-l-umber+ #\!)
                                                      :gfx-sym (tile-paint-value 11 13))
(define-basic-flavour '<potion> "icky green"          :text-sym (text-paint-value +term-green+ #\!)
                                                      :gfx-sym (tile-paint-value 11 17))
(define-basic-flavour '<potion> "azure"               :text-sym (text-paint-value +term-l-blue+ #\!)
                                                      :gfx-sym (tile-paint-value 11 4))
(define-basic-flavour '<potion> "blue"                :text-sym (text-paint-value +term-blue+ #\!)
                                                      :gfx-sym (tile-paint-value 11 5))
(define-basic-flavour '<potion> "blue speckled"       :text-sym (text-paint-value +term-blue+ #\!)
                                                      :gfx-sym (tile-paint-value 11 6))
(define-basic-flavour '<potion> "black"               :text-sym (text-paint-value +term-l-dark+ #\!)
                                                      :gfx-sym (tile-paint-value 11 0))
(define-basic-flavour '<potion> "brown"               :text-sym (text-paint-value +term-umber+ #\!)
                                                      :gfx-sym (tile-paint-value 11 8))
(define-basic-flavour '<potion> "brown speckled"      :text-sym (text-paint-value +term-umber+ #\!)
                                                      :gfx-sym (tile-paint-value 11 35))
(define-basic-flavour '<potion> "bubbling"            :text-sym (text-paint-value +term-white+ #\!)
                                                      :gfx-sym (tile-paint-value 11 56))
(define-basic-flavour '<potion> "chartreuse"          :text-sym (text-paint-value +term-green+ #\!)
                                                      :gfx-sym (tile-paint-value 11 17))
(define-basic-flavour '<potion> "cloudy"              :text-sym (text-paint-value +term-white+ #\!)
                                                      :gfx-sym (tile-paint-value 11 0))
(define-basic-flavour '<potion> "copper speckled"     :text-sym (text-paint-value +term-l-umber+ #\!)
                                                      :gfx-sym (tile-paint-value 11 19))
(define-basic-flavour '<potion> "crimson"             :text-sym (text-paint-value +term-red+ #\!)
                                                      :gfx-sym (tile-paint-value 11 18))
(define-basic-flavour '<potion> "cyan"                :text-sym (text-paint-value +term-l-blue+ #\!)
                                                      :gfx-sym (tile-paint-value 11 4))
(define-basic-flavour '<potion> "dark blue"           :text-sym (text-paint-value +term-blue+ #\!)
                                                      :gfx-sym (tile-paint-value 11 15))
(define-basic-flavour '<potion> "dark green"          :text-sym (text-paint-value +term-green+ #\!)
                                                      :gfx-sym (tile-paint-value 11 17))
(define-basic-flavour '<potion> "dark red"            :text-sym (text-paint-value +term-red+ #\!)
                                                      :gfx-sym (tile-paint-value 11 30))
(define-basic-flavour '<potion> "gold speckled"       :text-sym (text-paint-value +term-yellow+ #\!)
                                                      :gfx-sym (tile-paint-value 11 49))
(define-basic-flavour '<potion> "green"               :text-sym (text-paint-value +term-green+ #\!)
                                                      :gfx-sym (tile-paint-value 11 21))
(define-basic-flavour '<potion> "green speckled"      :text-sym (text-paint-value +term-green+ #\!)
                                                      :gfx-sym (tile-paint-value 11 27))
(define-basic-flavour '<potion> "grey"                :text-sym (text-paint-value +term-slate+ #\!)
                                                      :gfx-sym (tile-paint-value 11 24))
(define-basic-flavour '<potion> "grey speckled"       :text-sym (text-paint-value +term-slate+ #\!)
                                                      :gfx-sym (tile-paint-value 11 48))
(define-basic-flavour '<potion> "hazy"                :text-sym (text-paint-value +term-white+ #\!)
                                                      :gfx-sym (tile-paint-value 11 2))
(define-basic-flavour '<potion> "indigo"              :text-sym (text-paint-value +term-violet+ #\!)
                                                      :gfx-sym (tile-paint-value 11 46))
(define-basic-flavour '<potion> "light blue"          :text-sym (text-paint-value +term-l-blue+ #\!)
                                                      :gfx-sym (tile-paint-value 11 26))
(define-basic-flavour '<potion> "light green"         :text-sym (text-paint-value +term-green+ #\!)
                                                      :gfx-sym (tile-paint-value 11 21))
(define-basic-flavour '<potion> "magenta"             :text-sym (text-paint-value +term-red+ #\!)
                                                      :gfx-sym (tile-paint-value 11 41))
(define-basic-flavour '<potion> "metallic blue"       :text-sym (text-paint-value +term-blue+ #\!)
                                                      :gfx-sym (tile-paint-value 11 5))
(define-basic-flavour '<potion> "metallic red"        :text-sym (text-paint-value +term-red+ #\!)
                                                      :gfx-sym (tile-paint-value 11 28))
(define-basic-flavour '<potion> "metallic green"      :text-sym (text-paint-value +term-green+ #\!)
                                                      :gfx-sym (tile-paint-value 11 31))
(define-basic-flavour '<potion> "metallic purple"     :text-sym (text-paint-value +term-violet+ #\!)
                                                      :gfx-sym (tile-paint-value 11 32))
(define-basic-flavour '<potion> "misty"               :text-sym (text-paint-value +term-white+ #\!)
                                                      :gfx-sym (tile-paint-value 11 33))
(define-basic-flavour '<potion> "orange"              :text-sym (text-paint-value +term-orange+ #\!)
                                                      :gfx-sym (tile-paint-value 11 13))
(define-basic-flavour '<potion> "orange speckled"     :text-sym (text-paint-value +term-orange+ #\!)
                                                      :gfx-sym (tile-paint-value 11 35))
(define-basic-flavour '<potion> "pink"                :text-sym (text-paint-value +term-l-red+ #\!)
                                                      :gfx-sym (tile-paint-value 11 37))
(define-basic-flavour '<potion> "pink speckled"       :text-sym (text-paint-value +term-l-red+ #\!)
                                                      :gfx-sym (tile-paint-value 11 53))
(define-basic-flavour '<potion> "puce"                :text-sym (text-paint-value +term-violet+ #\!)
                                                      :gfx-sym (tile-paint-value 11 40))
(define-basic-flavour '<potion> "purple"              :text-sym (text-paint-value +term-violet+ #\!)
                                                      :gfx-sym (tile-paint-value 11 39))
(define-basic-flavour '<potion> "purple speckled"     :text-sym (text-paint-value +term-violet+ #\!)
                                                      :gfx-sym (tile-paint-value 11 40))
(define-basic-flavour '<potion> "red"                 :text-sym (text-paint-value +term-red+ #\!)
                                                      :gfx-sym (tile-paint-value 11 57))
(define-basic-flavour '<potion> "red speckled"        :text-sym (text-paint-value +term-red+ #\!)
                                                      :gfx-sym (tile-paint-value 11 41))
(define-basic-flavour '<potion> "silver speckled"     :text-sym (text-paint-value +term-white+ #\!)
                                                      :gfx-sym (tile-paint-value 11 48))
(define-basic-flavour '<potion> "smoky"               :text-sym (text-paint-value +term-l-dark+ #\!)
                                                      :gfx-sym (tile-paint-value 11 23))
(define-basic-flavour '<potion> "tangerine"           :text-sym (text-paint-value +term-orange+ #\!)
                                                      :gfx-sym (tile-paint-value 11 3))
(define-basic-flavour '<potion> "violet"              :text-sym (text-paint-value +term-violet+ #\!)
                                                      :gfx-sym (tile-paint-value 11 32))
(define-basic-flavour '<potion> "vermilion"           :text-sym (text-paint-value +term-red+ #\!)
                                                      :gfx-sym (tile-paint-value 11 47))
(define-basic-flavour '<potion> "white"               :text-sym (text-paint-value +term-white+ #\!)
                                                      :gfx-sym (tile-paint-value 11 48))
(define-basic-flavour '<potion> "yellow"              :text-sym (text-paint-value +term-yellow+ #\!)
                                                      :gfx-sym (tile-paint-value 11 58))
(define-basic-flavour '<potion> "violet speckled"     :text-sym (text-paint-value +term-violet+ #\!)
                                                      :gfx-sym (tile-paint-value 11 46))
(define-basic-flavour '<potion> "pungent"             :text-sym (text-paint-value +term-l-red+ #\!)
                                                      :gfx-sym (tile-paint-value 11 13))
(define-basic-flavour '<potion> "clotted red"         :text-sym (text-paint-value +term-red+ #\!)
                                                      :gfx-sym (tile-paint-value 11 3))
(define-basic-flavour '<potion> "viscous pink"        :text-sym (text-paint-value +term-l-red+ #\!)
                                                      :gfx-sym (tile-paint-value 11 36))
(define-basic-flavour '<potion> "oily yellow"         :text-sym (text-paint-value +term-yellow+ #\!)
                                                      :gfx-sym (tile-paint-value 11 11))
(define-basic-flavour '<potion> "gloopy green"        :text-sym (text-paint-value +term-green+ #\!)
                                                      :gfx-sym (tile-paint-value 11 17))
(define-basic-flavour '<potion> "shimmering"          :text-sym (text-paint-value +term-violet+ #\!)
                                                      :gfx-sym (tile-paint-value 11 46))
(define-basic-flavour '<potion> "coagulated crimson"  :text-sym (text-paint-value +term-red+ #\!)
                                                      :gfx-sym (tile-paint-value 11 18))
(define-basic-flavour '<potion> "yellow speckled"     :text-sym (text-paint-value +term-yellow+ #\!)
                                                      :gfx-sym (tile-paint-value 11 49))
(define-basic-flavour '<potion> "gold"                :text-sym (text-paint-value +term-yellow+ #\!)
                                                      :gfx-sym (tile-paint-value 11 58))


(define-basic-flavour '<mushroom> "blue"              :text-sym (text-paint-value +term-blue+ #\,)
                                                      :gfx-sym (tile-paint-value 5 13))
(define-basic-flavour '<mushroom> "black"             :text-sym (text-paint-value +term-l-dark+ #\,)
                                                      :gfx-sym (tile-paint-value 5 7))
(define-basic-flavour '<mushroom> "black spotted"     :text-sym (text-paint-value +term-l-dark+ #\,)
                                                      :gfx-sym (tile-paint-value 5 15))
(define-basic-flavour '<mushroom> "brown"             :text-sym (text-paint-value +term-umber+ #\,)
                                                      :gfx-sym (tile-paint-value 5 23))
(define-basic-flavour '<mushroom> "dark blue"         :text-sym (text-paint-value +term-blue+ #\,)
                                                      :gfx-sym (tile-paint-value 5 13))
(define-basic-flavour '<mushroom> "dark green"        :text-sym (text-paint-value +term-green+ #\,)
                                                      :gfx-sym (tile-paint-value 5 12))
(define-basic-flavour '<mushroom> "dark red"          :text-sym (text-paint-value +term-red+ #\,)
                                                      :gfx-sym (tile-paint-value 5 11))
(define-basic-flavour '<mushroom> "yellow"            :text-sym (text-paint-value +term-yellow+ #\,)
                                                      :gfx-sym (tile-paint-value 5 18))
(define-basic-flavour '<mushroom> "furry"             :text-sym (text-paint-value +term-white+ #\,)
                                                      :gfx-sym (tile-paint-value 5 16))
(define-basic-flavour '<mushroom> "green"             :text-sym (text-paint-value +term-green+ #\,)
                                                      :gfx-sym (tile-paint-value 5 21))
(define-basic-flavour '<mushroom> "grey"              :text-sym (text-paint-value +term-slate+ #\,)
                                                      :gfx-sym (tile-paint-value 5 16))
(define-basic-flavour '<mushroom> "light blue"        :text-sym (text-paint-value +term-l-blue+ #\,)
                                                      :gfx-sym (tile-paint-value 5 22))
(define-basic-flavour '<mushroom> "light green"       :text-sym (text-paint-value +term-green+ #\,)
                                                      :gfx-sym (tile-paint-value 5 21))
(define-basic-flavour '<mushroom> "violet"            :text-sym (text-paint-value +term-violet+ #\,)
                                                      :gfx-sym (tile-paint-value 5 17))
(define-basic-flavour '<mushroom> "red"               :text-sym (text-paint-value +term-red+ #\,)
                                                      :gfx-sym (tile-paint-value 5 20))
(define-basic-flavour '<mushroom> "slimy"             :text-sym (text-paint-value +term-slate+ #\,)
                                                      :gfx-sym (tile-paint-value 5 19))
(define-basic-flavour '<mushroom> "tan"               :text-sym (text-paint-value +term-l-umber+ #\,)
                                                      :gfx-sym (tile-paint-value 5 23))
(define-basic-flavour '<mushroom> "white"             :text-sym (text-paint-value +term-white+ #\,)
                                                      :gfx-sym (tile-paint-value 5 8))
(define-basic-flavour '<mushroom> "white spotted"     :text-sym (text-paint-value +term-white+ #\,)
                                                      :gfx-sym (tile-paint-value 5 16))
(define-basic-flavour '<mushroom> "wrinkled"          :text-sym (text-paint-value +term-umber+ #\,)
                                                      :gfx-sym (tile-paint-value 5 14))


(define-basic-flavour '<wand> "aluminium"             :text-sym (text-paint-value +term-l-blue+ #\-)
                                                      :gfx-sym (tile-paint-value 12 0))
(define-basic-flavour '<wand> "cast iron"             :text-sym (text-paint-value +term-l-dark+ #\-)
                                                      :gfx-sym (tile-paint-value 12 6))
(define-basic-flavour '<wand> "chromium"              :text-sym (text-paint-value +term-white+ #\-)
                                                      :gfx-sym (tile-paint-value 12 7))
(define-basic-flavour '<wand> "copper"                :text-sym (text-paint-value +term-l-umber+ #\-)
                                                      :gfx-sym (tile-paint-value 12 6))
(define-basic-flavour '<wand> "gold"                  :text-sym (text-paint-value +term-yellow+ #\-)
                                                      :gfx-sym (tile-paint-value 12 8))
(define-basic-flavour '<wand> "iron"                  :text-sym (text-paint-value +term-slate+ #\-)
                                                      :gfx-sym (tile-paint-value 12 5))
(define-basic-flavour '<wand> "magnesium"             :text-sym (text-paint-value +term-white+ #\-)
                                                      :gfx-sym (tile-paint-value 12 8))
(define-basic-flavour '<wand> "molybdenum"            :text-sym (text-paint-value +term-white+ #\-)
                                                      :gfx-sym (tile-paint-value 12 7))
(define-basic-flavour '<wand> "nickel"                :text-sym (text-paint-value +term-l-umber+ #\-)
                                                      :gfx-sym (tile-paint-value 12 4))
(define-basic-flavour '<wand> "rusty"                 :text-sym (text-paint-value +term-red+ #\-)
                                                      :gfx-sym (tile-paint-value 12 5))
(define-basic-flavour '<wand> "silver"                :text-sym (text-paint-value +term-white+ #\-)
                                                      :gfx-sym (tile-paint-value 12 0))
(define-basic-flavour '<wand> "steel"                 :text-sym (text-paint-value +term-white+ #\-)
                                                      :gfx-sym (tile-paint-value 12 1))
(define-basic-flavour '<wand> "tin"                   :text-sym (text-paint-value +term-white+ #\-)
                                                      :gfx-sym (tile-paint-value 12 1))
(define-basic-flavour '<wand> "titanium"              :text-sym (text-paint-value +term-white+ #\-)
                                                      :gfx-sym (tile-paint-value 12 6))
(define-basic-flavour '<wand> "tungsten"              :text-sym (text-paint-value +term-white+ #\-)
                                                      :gfx-sym (tile-paint-value 12 6))
(define-basic-flavour '<wand> "zirconium"             :text-sym (text-paint-value +term-white+ #\-)
                                                      :gfx-sym (tile-paint-value 12 7))
(define-basic-flavour '<wand> "zinc"                  :text-sym (text-paint-value +term-white+ #\-)
                                                      :gfx-sym (tile-paint-value 12 4))
(define-basic-flavour '<wand> "aluminum-plated"       :text-sym (text-paint-value +term-l-blue+ #\-)
                                                      :gfx-sym (tile-paint-value 12 11))
(define-basic-flavour '<wand> "copper-plated"         :text-sym (text-paint-value +term-l-umber+ #\-)
                                                      :gfx-sym (tile-paint-value 12 14))
(define-basic-flavour '<wand> "gold-plated"           :text-sym (text-paint-value +term-yellow+ #\-)
                                                      :gfx-sym (tile-paint-value 12 17))
(define-basic-flavour '<wand> "nickel-plated"         :text-sym (text-paint-value +term-l-umber+ #\-)
                                                      :gfx-sym (tile-paint-value 12 13))
(define-basic-flavour '<wand> "silver-plated"         :text-sym (text-paint-value +term-white+ #\-)
                                                      :gfx-sym (tile-paint-value 12 10))
(define-basic-flavour '<wand> "steel-plated"          :text-sym (text-paint-value +term-white+ #\-)
                                                      :gfx-sym (tile-paint-value 12 12))
(define-basic-flavour '<wand> "tin-plated"            :text-sym (text-paint-value +term-white+ #\-)
                                                      :gfx-sym (tile-paint-value 12 17))
(define-basic-flavour '<wand> "zinc-plated"           :text-sym (text-paint-value +term-white+ #\-)
                                                      :gfx-sym (tile-paint-value 12 15))
(define-basic-flavour '<wand> "mithril-plated"        :text-sym (text-paint-value +term-l-blue+ #\-)
                                                      :gfx-sym (tile-paint-value 12 13))
(define-basic-flavour '<wand> "mithril"               :text-sym (text-paint-value +term-l-blue+ #\-)
                                                      :gfx-sym (tile-paint-value 12 16))
(define-basic-flavour '<wand> "runed"                 :text-sym (text-paint-value +term-umber+ #\-)
                                                      :gfx-sym (tile-paint-value 12 11))
(define-basic-flavour '<wand> "bronze"                :text-sym (text-paint-value +term-l-umber+ #\-)
                                                      :gfx-sym (tile-paint-value 12 14))
(define-basic-flavour '<wand> "brass"                 :text-sym (text-paint-value +term-l-umber+ #\-)
                                                      :gfx-sym (tile-paint-value 12 15))
(define-basic-flavour '<wand> "platinum"              :text-sym (text-paint-value +term-white+ #\-)
                                                      :gfx-sym (tile-paint-value 12 13))
(define-basic-flavour '<wand> "lead"                  :text-sym (text-paint-value +term-slate+ #\-)
                                                      :gfx-sym (tile-paint-value 12 14))
(define-basic-flavour '<wand> "lead-plated"           :text-sym (text-paint-value +term-slate+ #\-)
                                                      :gfx-sym (tile-paint-value 12 15))
(define-basic-flavour '<wand> "ivory"                 :text-sym (text-paint-value +term-white+ #\-)
                                                      :gfx-sym (tile-paint-value 12 17))
(define-basic-flavour '<wand> "pewter"                :text-sym (text-paint-value +term-slate+ #\-)
                                                      :gfx-sym (tile-paint-value 12 13))


(define-basic-flavour '<staff> "aspen"                :text-sym (text-paint-value +term-l-umber+ #\_)
                                                      :gfx-sym (tile-paint-value 12 19))
(define-basic-flavour '<staff> "balsa"                :text-sym (text-paint-value +term-l-umber+ #\_)
                                                      :gfx-sym (tile-paint-value 12 19))
(define-basic-flavour '<staff> "banyan"               :text-sym (text-paint-value +term-l-umber+ #\_)
                                                      :gfx-sym (tile-paint-value 12 20))
(define-basic-flavour '<staff> "birch"                :text-sym (text-paint-value +term-l-umber+ #\_)
                                                      :gfx-sym (tile-paint-value 12 18))
(define-basic-flavour '<staff> "cedar"                :text-sym (text-paint-value +term-l-umber+ #\_)
                                                      :gfx-sym (tile-paint-value 12 22))
(define-basic-flavour '<staff> "cottonwood"           :text-sym (text-paint-value +term-l-umber+ #\_)
                                                      :gfx-sym (tile-paint-value 12 21))
(define-basic-flavour '<staff> "cypress"              :text-sym (text-paint-value +term-l-umber+ #\_)
                                                      :gfx-sym (tile-paint-value 12 22))
(define-basic-flavour '<staff> "dogwood"              :text-sym (text-paint-value +term-l-umber+ #\_)
                                                      :gfx-sym (tile-paint-value 12 24))
(define-basic-flavour '<staff> "elm"                  :text-sym (text-paint-value +term-l-umber+ #\_)
                                                      :gfx-sym (tile-paint-value 12 22))
(define-basic-flavour '<staff> "eucalyptus"           :text-sym (text-paint-value +term-l-umber+ #\_)
                                                      :gfx-sym (tile-paint-value 12 24))
(define-basic-flavour '<staff> "hemlock"              :text-sym (text-paint-value +term-l-umber+ #\_)
                                                      :gfx-sym (tile-paint-value 12 20))
(define-basic-flavour '<staff> "hickory"              :text-sym (text-paint-value +term-l-umber+ #\_)
                                                      :gfx-sym (tile-paint-value 12 22))
(define-basic-flavour '<staff> "ironwood"             :text-sym (text-paint-value +term-umber+ #\_)
                                                      :gfx-sym (tile-paint-value 12 21))
(define-basic-flavour '<staff> "locust"               :text-sym (text-paint-value +term-l-umber+ #\_)
                                                      :gfx-sym (tile-paint-value 12 20))
(define-basic-flavour '<staff> "mahogany"             :text-sym (text-paint-value +term-umber+ #\_)
                                                      :gfx-sym (tile-paint-value 12 20))
(define-basic-flavour '<staff> "maple"                :text-sym (text-paint-value +term-umber+ #\_)
                                                      :gfx-sym (tile-paint-value 12 22))
(define-basic-flavour '<staff> "mulberry"             :text-sym (text-paint-value +term-umber+ #\_)
                                                      :gfx-sym (tile-paint-value 12 20))
(define-basic-flavour '<staff> "oak"                  :text-sym (text-paint-value +term-umber+ #\_)
                                                      :gfx-sym (tile-paint-value 12 20))
(define-basic-flavour '<staff> "pine"                 :text-sym (text-paint-value +term-umber+ #\_)
                                                      :gfx-sym (tile-paint-value 12 24))
(define-basic-flavour '<staff> "redwood"              :text-sym (text-paint-value +term-red+ #\_)
                                                      :gfx-sym (tile-paint-value 12 20))
(define-basic-flavour '<staff> "rosewood"             :text-sym (text-paint-value +term-red+ #\_)
                                                      :gfx-sym (tile-paint-value 12 18))
(define-basic-flavour '<staff> "spruce"               :text-sym (text-paint-value +term-l-umber+ #\_)
                                                      :gfx-sym (tile-paint-value 12 18))
(define-basic-flavour '<staff> "sycamore"             :text-sym (text-paint-value +term-l-umber+ #\_)
                                                      :gfx-sym (tile-paint-value 12 19))
(define-basic-flavour '<staff> "teak"                 :text-sym (text-paint-value +term-l-umber+ #\_)
                                                      :gfx-sym (tile-paint-value 12 18))
(define-basic-flavour '<staff> "walnut"               :text-sym (text-paint-value +term-umber+ #\_)
                                                      :gfx-sym (tile-paint-value 12 19))
(define-basic-flavour '<staff> "mistletoe"            :text-sym (text-paint-value +term-green+ #\_)
                                                      :gfx-sym (tile-paint-value 12 22))
(define-basic-flavour '<staff> "hawthorn"             :text-sym (text-paint-value +term-l-umber+ #\_)
                                                      :gfx-sym (tile-paint-value 12 20))
(define-basic-flavour '<staff> "bamboo"               :text-sym (text-paint-value +term-l-umber+ #\_)
                                                      :gfx-sym (tile-paint-value 12 24))
(define-basic-flavour '<staff> "silver"               :text-sym (text-paint-value +term-white+ #\_)
                                                      :gfx-sym (tile-paint-value 12 23))
(define-basic-flavour '<staff> "runed"                :text-sym (text-paint-value +term-umber+ #\_)
                                                      :gfx-sym (tile-paint-value 12 24))
(define-basic-flavour '<staff> "golden"               :text-sym (text-paint-value +term-green+ #\_)
                                                      :gfx-sym (tile-paint-value 12 19))
(define-basic-flavour '<staff> "ashen"                :text-sym (text-paint-value +term-slate+ #\_)
                                                      :gfx-sym (tile-paint-value 12 21))
(define-basic-flavour '<staff> "gnarled"              :text-sym (text-paint-value +term-l-umber+ #\_)
                                                      :gfx-sym (tile-paint-value 12 19))
(define-basic-flavour '<staff> "ivory"                :text-sym (text-paint-value +term-white+ #\_)
                                                      :gfx-sym (tile-paint-value 12 22))
(define-basic-flavour '<staff> "willow"               :text-sym (text-paint-value +term-l-umber+ #\_)
                                                      :gfx-sym (tile-paint-value 12 21))


(define-basic-flavour '<amulet> "amber"               :text-sym (text-paint-value +term-yellow+ #\")
                                                      :gfx-sym (tile-paint-value 8 29))
(define-basic-flavour '<amulet> "driftwood"           :text-sym (text-paint-value +term-l-umber+ #\")
                                                      :gfx-sym (tile-paint-value 8 36))
(define-basic-flavour '<amulet> "coral"               :text-sym (text-paint-value +term-white+ #\")
                                                      :gfx-sym (tile-paint-value 8 39))
(define-basic-flavour '<amulet> "agate"               :text-sym (text-paint-value +term-white+ #\")
                                                      :gfx-sym (tile-paint-value 8 25))
(define-basic-flavour '<amulet> "ivory"               :text-sym (text-paint-value +term-white+ #\")
                                                      :gfx-sym (tile-paint-value 8 24))
(define-basic-flavour '<amulet> "obsidian"            :text-sym (text-paint-value +term-l-dark+ #\")
                                                      :gfx-sym (tile-paint-value 8 27))
(define-basic-flavour '<amulet> "bone"                :text-sym (text-paint-value +term-white+ #\")
                                                      :gfx-sym (tile-paint-value 8 24))
(define-basic-flavour '<amulet> "brass"               :text-sym (text-paint-value +term-l-umber+ #\")
                                                      :gfx-sym (tile-paint-value 8 34))
(define-basic-flavour '<amulet> "bronze"              :text-sym (text-paint-value +term-l-umber+ #\")
                                                      :gfx-sym (tile-paint-value 8 31))
(define-basic-flavour '<amulet> "pewter"              :text-sym (text-paint-value +term-slate+ #\")
                                                      :gfx-sym (tile-paint-value 8 32))
(define-basic-flavour '<amulet> "tortoise shell"      :text-sym (text-paint-value +term-umber+ #\")
                                                      :gfx-sym (tile-paint-value 8 30))
(define-basic-flavour '<amulet> "golden"              :text-sym (text-paint-value +term-yellow+ #\")
                                                      :gfx-sym (tile-paint-value 8 28))
(define-basic-flavour '<amulet> "azure"               :text-sym (text-paint-value +term-l-blue+ #\")
                                                      :gfx-sym (tile-paint-value 8 37))
(define-basic-flavour '<amulet> "crystal"             :text-sym (text-paint-value +term-white+ #\")
                                                      :gfx-sym (tile-paint-value 8 24))
(define-basic-flavour '<amulet> "silver"              :text-sym (text-paint-value +term-white+ #\")
                                                      :gfx-sym (tile-paint-value 8 25))
(define-basic-flavour '<amulet> "copper"              :text-sym (text-paint-value +term-l-umber+ #\")
                                                      :gfx-sym (tile-paint-value 8 34))
(define-basic-flavour '<amulet> "carved oak"          :text-sym (text-paint-value +term-umber+ #\")
                                                      :gfx-sym (tile-paint-value 8 39))
(define-basic-flavour '<amulet> "dragon tooth"        :text-sym (text-paint-value +term-white+ #\")
                                                      :gfx-sym (tile-paint-value 8 24))
(define-basic-flavour '<amulet> "ruby"                :text-sym (text-paint-value +term-red+ #\")
                                                      :gfx-sym (tile-paint-value 8 31))
(define-basic-flavour '<amulet> "mithril"             :text-sym (text-paint-value +term-l-blue+ #\")
                                                      :gfx-sym (tile-paint-value 8 37))
(define-basic-flavour '<amulet> "adamant"             :text-sym (text-paint-value +term-green+ #\")
                                                      :gfx-sym (tile-paint-value 8 34))
(define-basic-flavour '<amulet> "flint stone"         :text-sym (text-paint-value +term-slate+ #\")
                                                      :gfx-sym (tile-paint-value 8 26))
(define-basic-flavour '<amulet> "sea shell"           :text-sym (text-paint-value +term-l-blue+ #\")
                                                      :gfx-sym (tile-paint-value 8 37))
(define-basic-flavour '<amulet> "mother-of-pearl"     :text-sym (text-paint-value +term-white+ #\")
                                                      :gfx-sym (tile-paint-value 8 25))


(define-basic-flavour '<ring> "adamantite"            :text-sym (text-paint-value +term-green+ #\=)
                                                      :gfx-sym (tile-paint-value 8 12))
(define-basic-flavour '<ring> "alexandrite"           :text-sym (text-paint-value +term-green+ #\=)
                                                      :gfx-sym (tile-paint-value 8 4))
(define-basic-flavour '<ring> "amethyst"              :text-sym (text-paint-value +term-violet+ #\=)
                                                      :gfx-sym (tile-paint-value 8 9))
(define-basic-flavour '<ring> "aquamarine"            :text-sym (text-paint-value +term-l-blue+ #\=)
                                                      :gfx-sym (tile-paint-value 8 13))
(define-basic-flavour '<ring> "azurite"               :text-sym (text-paint-value +term-l-blue+ #\=)
                                                      :gfx-sym (tile-paint-value 8 13))
(define-basic-flavour '<ring> "beryl"                 :text-sym (text-paint-value +term-green+ #\=)
                                                      :gfx-sym (tile-paint-value 8 12))
(define-basic-flavour '<ring> "bloodstone"            :text-sym (text-paint-value +term-red+ #\=)
                                                      :gfx-sym (tile-paint-value 8 3))
(define-basic-flavour '<ring> "calcite"               :text-sym (text-paint-value +term-white+ #\=)
                                                      :gfx-sym (tile-paint-value 8 0))
(define-basic-flavour '<ring> "carnelian"             :text-sym (text-paint-value +term-red+ #\=)
                                                      :gfx-sym (tile-paint-value 8 3))
(define-basic-flavour '<ring> "corundum"              :text-sym (text-paint-value +term-slate+ #\=)
                                                      :gfx-sym (tile-paint-value 8 8))
(define-basic-flavour '<ring> "diamond"               :text-sym (text-paint-value +term-white+ #\=)
                                                      :gfx-sym (tile-paint-value 8 0))
(define-basic-flavour '<ring> "emerald"               :text-sym (text-paint-value +term-green+ #\=)
                                                      :gfx-sym (tile-paint-value 8 4))
(define-basic-flavour '<ring> "fluorite"              :text-sym (text-paint-value +term-green+ #\=)
                                                      :gfx-sym (tile-paint-value 8 12))
(define-basic-flavour '<ring> "garnet"                :text-sym (text-paint-value +term-red+ #\=)
                                                      :gfx-sym (tile-paint-value 8 3))
(define-basic-flavour '<ring> "granite"               :text-sym (text-paint-value +term-white+ #\=)
                                                      :gfx-sym (tile-paint-value 8 1))
(define-basic-flavour '<ring> "jade"                  :text-sym (text-paint-value +term-green+ #\=)
                                                      :gfx-sym (tile-paint-value 8 12))
(define-basic-flavour '<ring> "jasper"                :text-sym (text-paint-value +term-umber+ #\=)
                                                      :gfx-sym (tile-paint-value 8 6))
(define-basic-flavour '<ring> "lapis lazuli"          :text-sym (text-paint-value +term-blue+ #\=)
                                                      :gfx-sym (tile-paint-value 8 5))
(define-basic-flavour '<ring> "malachite"             :text-sym (text-paint-value +term-green+ #\=)
                                                      :gfx-sym (tile-paint-value 8 4))
(define-basic-flavour '<ring> "marble"                :text-sym (text-paint-value +term-white+ #\=)
                                                      :gfx-sym (tile-paint-value 8 0))
(define-basic-flavour '<ring> "moonstone"             :text-sym (text-paint-value +term-white+ #\=)
                                                      :gfx-sym (tile-paint-value 8 1))
(define-basic-flavour '<ring> "onyx"                  :text-sym (text-paint-value +term-l-red+ #\=)
                                                      :gfx-sym (tile-paint-value 8 11))
(define-basic-flavour '<ring> "opal"                  :text-sym (text-paint-value +term-white+ #\=)
                                                      :gfx-sym (tile-paint-value 8 1))
(define-basic-flavour '<ring> "pearl"                 :text-sym (text-paint-value +term-white+ #\=)
                                                      :gfx-sym (tile-paint-value 8 0))
(define-basic-flavour '<ring> "quartz"                :text-sym (text-paint-value +term-white+ #\=)
                                                      :gfx-sym (tile-paint-value 8 1))
(define-basic-flavour '<ring> "quartzite"             :text-sym (text-paint-value +term-white+ #\=)
                                                      :gfx-sym (tile-paint-value 8 1))
(define-basic-flavour '<ring> "rhodonite"             :text-sym (text-paint-value +term-l-red+ #\=)
                                                      :gfx-sym (tile-paint-value 8 11))
(define-basic-flavour '<ring> "ruby"                  :text-sym (text-paint-value +term-red+ #\=)
                                                      :gfx-sym (tile-paint-value 8 3))
(define-basic-flavour '<ring> "sapphire"              :text-sym (text-paint-value +term-blue+ #\=)
                                                      :gfx-sym (tile-paint-value 8 5))
(define-basic-flavour '<ring> "tiger eye"             :text-sym (text-paint-value +term-yellow+ #\=)
                                                      :gfx-sym (tile-paint-value 8 10))
(define-basic-flavour '<ring> "topaz"                 :text-sym (text-paint-value +term-yellow+ #\=)
                                                      :gfx-sym (tile-paint-value 8 10))
(define-basic-flavour '<ring> "turquoise"             :text-sym (text-paint-value +term-l-blue+ #\=)
                                                      :gfx-sym (tile-paint-value 8 13))
(define-basic-flavour '<ring> "zircon"                :text-sym (text-paint-value +term-l-umber+ #\=)
                                                      :gfx-sym (tile-paint-value 8 14))
(define-basic-flavour '<ring> "platinum"              :text-sym (text-paint-value +term-white+ #\=)
                                                      :gfx-sym (tile-paint-value 8 0))
(define-basic-flavour '<ring> "bronze"                :text-sym (text-paint-value +term-l-umber+ #\=)
                                                      :gfx-sym (tile-paint-value 8 14))
(define-basic-flavour '<ring> "gold"                  :text-sym (text-paint-value +term-yellow+ #\=)
                                                      :gfx-sym (tile-paint-value 8 10))
(define-basic-flavour '<ring> "obsidian"              :text-sym (text-paint-value +term-l-dark+ #\=)
                                                      :gfx-sym (tile-paint-value 8 1))
(define-basic-flavour '<ring> "silver"                :text-sym (text-paint-value +term-white+ #\=)
                                                      :gfx-sym (tile-paint-value 8 1))
(define-basic-flavour '<ring> "tortoise shell"        :text-sym (text-paint-value +term-umber+ #\=)
                                                      :gfx-sym (tile-paint-value 8 6))
(define-basic-flavour '<ring> "mithril"               :text-sym (text-paint-value +term-l-blue+ #\=)
                                                      :gfx-sym (tile-paint-value 8 13))
(define-basic-flavour '<ring> "jet"                   :text-sym (text-paint-value +term-l-dark+ #\=)
                                                      :gfx-sym (tile-paint-value 8 1))
(define-basic-flavour '<ring> "engagement"            :text-sym (text-paint-value +term-yellow+ #\=)
                                                      :gfx-sym (tile-paint-value 8 10))
(define-basic-flavour '<ring> "plain gold"            :text-sym (text-paint-value +term-yellow+ #\=)
                                                      :gfx-sym (tile-paint-value 8 23))


(define-basic-flavour '<rod> "aluminum"               :text-sym (text-paint-value +term-l-blue+ #\-)
                                                      :gfx-sym (tile-paint-value 12 13))
(define-basic-flavour '<rod> "cast iron"              :text-sym (text-paint-value +term-l-dark+ #\-)
                                                      :gfx-sym (tile-paint-value 12 10))
(define-basic-flavour '<rod> "chromium"               :text-sym (text-paint-value +term-white+ #\-)
                                                      :gfx-sym (tile-paint-value 12 10))
(define-basic-flavour '<rod> "copper"                 :text-sym (text-paint-value +term-l-umber+ #\-)
                                                      :gfx-sym (tile-paint-value 12 10))
(define-basic-flavour '<rod> "gold"                   :text-sym (text-paint-value +term-yellow+ #\-)
                                                      :gfx-sym (tile-paint-value 12 17))
(define-basic-flavour '<rod> "iron"                   :text-sym (text-paint-value +term-slate+ #\-)
                                                      :gfx-sym (tile-paint-value 12 15))
(define-basic-flavour '<rod> "magnesium"              :text-sym (text-paint-value +term-white+ #\-)
                                                      :gfx-sym (tile-paint-value 12 13))
(define-basic-flavour '<rod> "molybdenum"             :text-sym (text-paint-value +term-white+ #\-)
                                                      :gfx-sym (tile-paint-value 12 16))
(define-basic-flavour '<rod> "nickel"                 :text-sym (text-paint-value +term-l-umber+ #\-)
                                                      :gfx-sym (tile-paint-value 12 14))
(define-basic-flavour '<rod> "rusty"                  :text-sym (text-paint-value +term-red+ #\-)
                                                      :gfx-sym (tile-paint-value 12 12))
(define-basic-flavour '<rod> "silver"                 :text-sym (text-paint-value +term-white+ #\-)
                                                      :gfx-sym (tile-paint-value 12 9))
(define-basic-flavour '<rod> "steel"                  :text-sym (text-paint-value +term-white+ #\-)
                                                      :gfx-sym (tile-paint-value 12 13))
(define-basic-flavour '<rod> "tin"                    :text-sym (text-paint-value +term-white+ #\-)
                                                      :gfx-sym (tile-paint-value 12 16))
(define-basic-flavour '<rod> "titanium"               :text-sym (text-paint-value +term-white+ #\-)
                                                      :gfx-sym (tile-paint-value 12 11))
(define-basic-flavour '<rod> "tungsten"               :text-sym (text-paint-value +term-white+ #\-)
                                                      :gfx-sym (tile-paint-value 12 11))
(define-basic-flavour '<rod> "zirconium"              :text-sym (text-paint-value +term-white+ #\-)
                                                      :gfx-sym (tile-paint-value 12 11))
(define-basic-flavour '<rod> "zinc"                   :text-sym (text-paint-value +term-white+ #\-)
                                                      :gfx-sym (tile-paint-value 12 14))
(define-basic-flavour '<rod> "aluminum-plated"        :text-sym (text-paint-value +term-l-blue+ #\-)
                                                      :gfx-sym (tile-paint-value 12 13))
(define-basic-flavour '<rod> "copper-plated"          :text-sym (text-paint-value +term-l-umber+ #\-)
                                                      :gfx-sym (tile-paint-value 12 14))
(define-basic-flavour '<rod> "gold-plated"            :text-sym (text-paint-value +term-yellow+ #\-)
                                                      :gfx-sym (tile-paint-value 12 10))
(define-basic-flavour '<rod> "nickel-plated"          :text-sym (text-paint-value +term-l-umber+ #\-)
                                                      :gfx-sym (tile-paint-value 12 14))
(define-basic-flavour '<rod> "silver-plated"          :text-sym (text-paint-value +term-white+ #\-)
                                                      :gfx-sym (tile-paint-value 12 13))
(define-basic-flavour '<rod> "steel-plated"           :text-sym (text-paint-value +term-white+ #\-)
                                                      :gfx-sym (tile-paint-value 12 10))
(define-basic-flavour '<rod> "tin-plated"             :text-sym (text-paint-value +term-white+ #\-)
                                                      :gfx-sym (tile-paint-value 12 9))
(define-basic-flavour '<rod> "zinc-plated"            :text-sym (text-paint-value +term-white+ #\-)
                                                      :gfx-sym (tile-paint-value 12 12))
(define-basic-flavour '<rod> "mithril-plated"         :text-sym (text-paint-value +term-l-blue+ #\-)
                                                      :gfx-sym (tile-paint-value 12 16))
(define-basic-flavour '<rod> "mithril"                :text-sym (text-paint-value +term-l-blue+ #\-)
                                                      :gfx-sym (tile-paint-value 12 16))
(define-basic-flavour '<rod> "runed"                  :text-sym (text-paint-value +term-umber+ #\-)
                                                      :gfx-sym (tile-paint-value 12 10))
(define-basic-flavour '<rod> "bronze"                 :text-sym (text-paint-value +term-l-umber+ #\-)
                                                      :gfx-sym (tile-paint-value 12 14))
(define-basic-flavour '<rod> "brass"                  :text-sym (text-paint-value +term-l-umber+ #\-)
                                                      :gfx-sym (tile-paint-value 12 15))
(define-basic-flavour '<rod> "platinum"               :text-sym (text-paint-value +term-white+ #\-)
                                                      :gfx-sym (tile-paint-value 12 13))
(define-basic-flavour '<rod> "lead"                   :text-sym (text-paint-value +term-slate+ #\-)
                                                      :gfx-sym (tile-paint-value 12 12))
(define-basic-flavour '<rod> "lead-plated"            :text-sym (text-paint-value +term-slate+ #\-)
                                                      :gfx-sym (tile-paint-value 12 15))
(define-basic-flavour '<rod> "ivory"                  :text-sym (text-paint-value +term-white+ #\-)
                                                      :gfx-sym (tile-paint-value 12 17))
(define-basic-flavour '<rod> "pewter"                 :text-sym (text-paint-value +term-slate+ #\-)
                                                      :gfx-sym (tile-paint-value 12 15))


;; the scroll functionality is in various.lisp and is compiled. 
;; time to add the scroll flavour type
(define-flavour-type '<scroll> :generator-fn #'van-generate-scroll-flavour
		     :text-sym (text-paint-value +term-white+ #\?))
