CLEANFILES=*.o *.so *.fasl *.faslmt *.x86f *.err *.fas *.fsl *.ufsl *.lib *.sparcf *~ *.dfsl *.ofasl

all: 


clean:
	if test -d config; then cd config && $(RM) $(CLEANFILES); fi
	$(RM) $(CLEANFILES)

lisp-clean: clean
